##Consultar desde el gateway http://localhost:5224/ms-books-payments/api/v1/payments
server:
  port: 5215
  servlet:
    context-path: '/api/v1/payments'
spring:
  application:
    name: ms-books-payments
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentsdb
    username: payments
    password: R3l4t0SP4ym3ntS
## Configuración CLiente Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:5223/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-payments