server:
  port: 5227
  servlet:
    context-path: '/api/v1/catalogue'
spring:
  application:
    name: ms-books-catalogue
  datasource:
    url: jdbc:postgresql://localhost:5432/cataloguedb
    username: catalogue
    password: R3l4t0SC4t4l0gu3
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddres: true
    hostname: ms-books-payments